// <auto-generated />
using System;
using Canhoes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Canhoes.Api.Migrations
{
    [DbContext(typeof(CanhoesDbContext))]
    partial class CanhoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Canhoes.Api.Models.AwardCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("VoteQuestion")
                        .HasColumnType("text");

                    b.Property<string>("VoteRules")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AwardCategories_IsActive");

                    b.HasIndex("EventId", "IsActive")
                        .HasDatabaseName("IX_AwardCategories_EventId_IsActive");

                    b.HasIndex("EventId", "SortOrder");

                    b.ToTable("AwardCategories");
                });

            modelBuilder.Entity("Canhoes.Api.Models.CanhoesEventStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleVisibilityJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<bool>("NominationsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResultsVisible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("CanhoesEventState");
                });

            modelBuilder.Entity("Canhoes.Api.Models.CategoryProposalEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedByUserId")
                        .HasDatabaseName("IX_CategoryProposals_ProposedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("EventId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_CategoryProposals_EventId_Status_CreatedAtUtc");

                    b.ToTable("CategoryProposals");
                });

            modelBuilder.Entity("Canhoes.Api.Models.EventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Canhoes.Api.Models.EventMemberEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Role")
                        .HasDatabaseName("IX_EventMembers_EventId_Role");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventMembers");
                });

            modelBuilder.Entity("Canhoes.Api.Models.EventPhaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "IsActive");

                    b.HasIndex("EventId", "Type")
                        .IsUnique();

                    b.ToTable("EventPhases");
                });

            modelBuilder.Entity("Canhoes.Api.Models.GalaMeasureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "IsActive")
                        .HasDatabaseName("IX_Measures_EventId_IsActive");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostCommentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("HubPostComments");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostCommentReactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CommentId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("HubPostCommentReactions");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostDownvoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("HubPostDownvotes");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MediaUrlsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("IX_HubPosts_AuthorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsPinned");

                    b.HasIndex("EventId", "IsPinned", "CreatedAtUtc")
                        .HasDatabaseName("IX_HubPosts_EventId_IsPinned_CreatedAtUtc");

                    b.ToTable("HubPosts");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostLikeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("HubPostLikes");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostMediaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("PostId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("HubPostMedia");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostPollEntity", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("PostId");

                    b.ToTable("HubPostPolls");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostPollOptionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "SortOrder");

                    b.ToTable("HubPostPollOptions");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostPollVoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_HubPostPollVotes_UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("HubPostPollVotes");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostReactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("HubPostReactions");
                });

            modelBuilder.Entity("Canhoes.Api.Models.MeasureProposalEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposedByUserId")
                        .HasDatabaseName("IX_MeasureProposals_ProposedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("EventId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_MeasureProposals_EventId_Status_CreatedAtUtc");

                    b.ToTable("MeasureProposals");
                });

            modelBuilder.Entity("Canhoes.Api.Models.NomineeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmissionKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId")
                        .HasDatabaseName("IX_Nominees_SubmittedByUserId");

                    b.HasIndex("CategoryId", "Status");

                    b.HasIndex("EventId", "Status");

                    b.HasIndex("EventId", "Status", "CategoryId")
                        .HasDatabaseName("IX_Nominees_EventId_Status_CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("Canhoes.Api.Models.SecretSantaAssignmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DrawId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GiverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DrawId")
                        .HasDatabaseName("IX_SecretSantaAssignments_DrawId");

                    b.HasIndex("GiverUserId")
                        .HasDatabaseName("IX_SecretSantaAssignments_GiverUserId");

                    b.HasIndex("ReceiverUserId")
                        .HasDatabaseName("IX_SecretSantaAssignments_ReceiverUserId");

                    b.ToTable("SecretSantaAssignments");
                });

            modelBuilder.Entity("Canhoes.Api.Models.SecretSantaDrawEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventCode")
                        .HasDatabaseName("IX_SecretSantaDraws_EventCode");

                    b.ToTable("SecretSantaDraws");
                });

            modelBuilder.Entity("Canhoes.Api.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Canhoes.Api.Models.UserVoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_UserVotes_TargetUserId");

                    b.HasIndex("CategoryId", "VoterUserId")
                        .IsUnique();

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("Canhoes.Api.Models.VoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomineeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId")
                        .HasDatabaseName("IX_Votes_NomineeId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Votes_UserId");

                    b.HasIndex("CategoryId", "UserId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Canhoes.Api.Models.WishlistItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_WishlistItems_EventId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WishlistItems_UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostCommentEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostCommentReactionEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostCommentEntity", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostDownvoteEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostLikeEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostMediaEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostPollEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostPollOptionEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostPollEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostPollVoteEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostPollEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Canhoes.Api.Models.HubPostReactionEntity", b =>
                {
                    b.HasOne("Canhoes.Api.Models.HubPostEntity", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
